# Generated by Django 6.0.4 on 2026-05-02 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(max_length=200, verbose_name='Вариант А')),
                ('option_b', models.CharField(max_length=200, verbose_name='Вариант Б')),
                ('coin_result', models.CharField(blank=True, max_length=200, verbose_name='Что выпало')),
                ('counter_arguments', models.JSONField(default=list, verbose_name='Контраргументы')),
                ('final_choice', models.CharField(blank=True, max_length=200, verbose_name='Итоговый выбор')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
    ]
