# Generated by Django 6.0.4 on 2026-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='from_cache',
            field=models.BooleanField(default=False, verbose_name='Из кэша'),
        ),
        migrations.AddField(
            model_name='decision',
            name='used_deepseek',
            field=models.BooleanField(default=False, verbose_name='Использован DeepSeek'),
        ),
    ]
