# Generated by Django 6.0.4 on 2026-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_decision_from_cache_decision_used_deepseek'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='provocative_question',
            field=models.TextField(blank=True, verbose_name='Провокационный вопрос'),
        ),
    ]
