# Generated by Django 6.0.4 on 2026-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_decision_provocative_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='mode',
            field=models.CharField(default='cynic', max_length=20, verbose_name='Режим спорщика'),
        ),
    ]
