# Generated by Django 6.0.4 on 2026-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0004_decision_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('mode', models.CharField(default='cynic', max_length=20)),
                ('coin_result', models.CharField(blank=True, max_length=200)),
                ('counter_arguments', models.JSONField(default=list)),
                ('provocative_question', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['option_a', 'option_b', 'mode'], name='decisions_c_option__e97ea9_idx')],
            },
        ),
    ]
